
development:
  host: locahost
  adapter: postgresql
  encoding: unicode
  database: adnconsult_development
  pool: 5
  username: mrhindicacao
  password: mrhindicacao

test:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: adnconsult_test
  pool: 5
  username: mrhindicacao
  password: mrhindicacao

production:
  host: localhost
  adapter: postgresql
  encoding: unicode
  database: adnconsult_production
  pool: 5
  username: mrhindicacao
  password: mrhindicacao
